version: "3"
services:
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: "xxx"
      POSTGRES_PASSWORD: "changeme"
      POSTGRES_DB: "pip"
    ports:
      - "5432:5432"

  postgres-test:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: "xxx"
      POSTGRES_PASSWORD: "changeme"
      POSTGRES_DB: "pip"
    ports:
      - "5433:5432"

  pip:
    image: bkowalik:demo
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: 5432
      POSTGRES_USER: "xxx"
      POSTGRES_PASSWORD: "changeme"
      POSTGRES_DB: "pip"
    ports:
      - "9000:9000"
    links:
      - postgres
